# Generated by Django 2.2.12 on 2020-05-30 07:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("home", "0002_load_initial_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="customtext",
            name="gfgfd",
            field=models.ManyToManyField(
                blank=True, related_name="customtext_gfgfd", to="home.HomePage"
            ),
        ),
        migrations.AddField(
            model_name="customtext",
            name="tfryrhgf",
            field=models.ManyToManyField(
                blank=True,
                related_name="customtext_tfryrhgf",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
