# Generated by Django 2.2.12 on 2020-05-30 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200530_0716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customtext',
            name='gfgfd',
        ),
        migrations.RemoveField(
            model_name='customtext',
            name='tfryrhgf',
        ),
    ]
